/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioIndexRouteImport } from './routes/_studio/index'
import { Route as StudioCreateRouteImport } from './routes/_studio/create'
import { Route as StudioExploreRouteImport } from './routes/_studio/explore'
import { Route as StudioInboxRouteRouteImport } from './routes/_studio/inbox/route'
import { Route as StudioLibraryRouteImport } from './routes/_studio/library'
import { Route as StudioProfileRouteImport } from './routes/_studio/profile'
import { Route as StudioBeatIdRouteImport } from './routes/_studio/beat.$id'
import { Route as StudioInboxIndexRouteImport } from './routes/_studio/inbox/index'
import { Route as StudioInboxRoomIdRouteImport } from './routes/_studio/inbox/$roomId'
import { Route as StudioTrackIdRouteImport } from './routes/_studio/track.$id'
import { Route as StudioUUsernameRouteImport } from './routes/_studio/u.$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCreateRoute = StudioCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => StudioRoute,
} as any)
const StudioExploreRoute = StudioExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInboxRouteRoute = StudioInboxRouteRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLibraryRoute = StudioLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudioRoute,
} as any)
const StudioProfileRoute = StudioProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBeatIdRoute = StudioBeatIdRouteImport.update({
  id: '/beat/$id',
  path: '/beat/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInboxIndexRoute = StudioInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioInboxRouteRoute,
} as any)
const StudioInboxRoomIdRoute = StudioInboxRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => StudioInboxRouteRoute,
} as any)
const StudioTrackIdRoute = StudioTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioUUsernameRoute = StudioUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/login': typeof LoginRoute
  '/inbox': typeof StudioInboxRouteRouteWithChildren
  '/create': typeof StudioCreateRoute
  '/explore': typeof StudioExploreRoute
  '/library': typeof StudioLibraryRoute
  '/profile': typeof StudioProfileRoute
  '/beat/$id': typeof StudioBeatIdRoute
  '/inbox/$roomId': typeof StudioInboxRoomIdRoute
  '/track/$id': typeof StudioTrackIdRoute
  '/u/$username': typeof StudioUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/inbox/': typeof StudioInboxIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/create': typeof StudioCreateRoute
  '/explore': typeof StudioExploreRoute
  '/library': typeof StudioLibraryRoute
  '/profile': typeof StudioProfileRoute
  '/': typeof StudioIndexRoute
  '/beat/$id': typeof StudioBeatIdRoute
  '/inbox/$roomId': typeof StudioInboxRoomIdRoute
  '/track/$id': typeof StudioTrackIdRoute
  '/u/$username': typeof StudioUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/inbox': typeof StudioInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteWithChildren
  '/login': typeof LoginRoute
  '/_studio/inbox': typeof StudioInboxRouteRouteWithChildren
  '/_studio/create': typeof StudioCreateRoute
  '/_studio/explore': typeof StudioExploreRoute
  '/_studio/library': typeof StudioLibraryRoute
  '/_studio/profile': typeof StudioProfileRoute
  '/_studio/': typeof StudioIndexRoute
  '/_studio/beat/$id': typeof StudioBeatIdRoute
  '/_studio/inbox/$roomId': typeof StudioInboxRoomIdRoute
  '/_studio/track/$id': typeof StudioTrackIdRoute
  '/_studio/u/$username': typeof StudioUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_studio/inbox/': typeof StudioInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inbox'
    | '/create'
    | '/explore'
    | '/library'
    | '/profile'
    | '/beat/$id'
    | '/inbox/$roomId'
    | '/track/$id'
    | '/u/$username'
    | '/api/auth/$'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/create'
    | '/explore'
    | '/library'
    | '/profile'
    | '/'
    | '/beat/$id'
    | '/inbox/$roomId'
    | '/track/$id'
    | '/u/$username'
    | '/api/auth/$'
    | '/inbox'
  id:
    | '__root__'
    | '/_studio'
    | '/login'
    | '/_studio/inbox'
    | '/_studio/create'
    | '/_studio/explore'
    | '/_studio/library'
    | '/_studio/profile'
    | '/_studio/'
    | '/_studio/beat/$id'
    | '/_studio/inbox/$roomId'
    | '/_studio/track/$id'
    | '/_studio/u/$username'
    | '/api/auth/$'
    | '/_studio/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/create': {
      id: '/_studio/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof StudioCreateRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/explore': {
      id: '/_studio/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof StudioExploreRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/inbox': {
      id: '/_studio/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof StudioInboxRouteRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/library': {
      id: '/_studio/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof StudioLibraryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/profile': {
      id: '/_studio/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof StudioProfileRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/beat/$id': {
      id: '/_studio/beat/$id'
      path: '/beat/$id'
      fullPath: '/beat/$id'
      preLoaderRoute: typeof StudioBeatIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/inbox/': {
      id: '/_studio/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof StudioInboxIndexRouteImport
      parentRoute: typeof StudioInboxRouteRoute
    }
    '/_studio/inbox/$roomId': {
      id: '/_studio/inbox/$roomId'
      path: '/$roomId'
      fullPath: '/inbox/$roomId'
      preLoaderRoute: typeof StudioInboxRoomIdRouteImport
      parentRoute: typeof StudioInboxRouteRoute
    }
    '/_studio/track/$id': {
      id: '/_studio/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof StudioTrackIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/u/$username': {
      id: '/_studio/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof StudioUUsernameRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioInboxRouteRouteChildren {
  StudioInboxRoomIdRoute: typeof StudioInboxRoomIdRoute
  StudioInboxIndexRoute: typeof StudioInboxIndexRoute
}

const StudioInboxRouteRouteChildren: StudioInboxRouteRouteChildren = {
  StudioInboxRoomIdRoute: StudioInboxRoomIdRoute,
  StudioInboxIndexRoute: StudioInboxIndexRoute,
}

const StudioInboxRouteRouteWithChildren =
  StudioInboxRouteRoute._addFileChildren(StudioInboxRouteRouteChildren)

interface StudioRouteChildren {
  StudioInboxRouteRoute: typeof StudioInboxRouteRouteWithChildren
  StudioCreateRoute: typeof StudioCreateRoute
  StudioExploreRoute: typeof StudioExploreRoute
  StudioLibraryRoute: typeof StudioLibraryRoute
  StudioProfileRoute: typeof StudioProfileRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioBeatIdRoute: typeof StudioBeatIdRoute
  StudioTrackIdRoute: typeof StudioTrackIdRoute
  StudioUUsernameRoute: typeof StudioUUsernameRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioInboxRouteRoute: StudioInboxRouteRouteWithChildren,
  StudioCreateRoute: StudioCreateRoute,
  StudioExploreRoute: StudioExploreRoute,
  StudioLibraryRoute: StudioLibraryRoute,
  StudioProfileRoute: StudioProfileRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioBeatIdRoute: StudioBeatIdRoute,
  StudioTrackIdRoute: StudioTrackIdRoute,
  StudioUUsernameRoute: StudioUUsernameRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
