package com.nexora.music;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.view.WindowInsets;
import android.view.animation.AccelerateDecelerateInterpolator;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class MainActivity extends Activity {
    private static final int BG=Color.rgb(8,9,15), SURFACE=Color.rgb(18,20,29), SURFACE2=Color.rgb(27,29,41), TEXT=Color.rgb(246,247,251), MUTED=Color.rgb(150,155,170), ACCENT=Color.rgb(125,92,255), GREEN=Color.rgb(76,205,135);
    private SupabaseClient supabase; private NexoraApiClient api; private SupabaseRealtimeClient realtime;
    private LinearLayout content, navigation; private final Handler handler=new Handler(Looper.getMainLooper()); private Runnable authPoll; private String userId; private String openChatId;

    @Override protected void onCreate(Bundle state){ super.onCreate(state); getWindow().setStatusBarColor(BG); getWindow().setNavigationBarColor(BG); supabase=new SupabaseClient(this); api=new NexoraApiClient(); realtime=new SupabaseRealtimeClient(); if(!supabase.isSignedIn()&&!getPreferences(MODE_PRIVATE).getBoolean("welcome_seen",false)) showWelcome(); else loadUserAndShowChats(); }
    private void loadUserAndShowChats(){ supabase.getCurrentUser(new SupabaseClient.Callback(){ public void onSuccess(String s){ try{userId=JsonParser.parseString(s).getAsJsonObject().get("id").getAsString();}catch(Exception ignored){} runOnUiThread(MainActivity.this::showChats);} public void onError(Exception e){supabase.signOut();runOnUiThread(MainActivity.this::showWelcome);} }); }

    private void showWelcome(){ LinearLayout root=baseRoot(); root.setGravity(Gravity.CENTER); LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setGravity(Gravity.CENTER_HORIZONTAL); box.setPadding(dp(28),dp(24),dp(28),dp(24)); ImageView logo=new ImageView(this); logo.setImageResource(R.drawable.nexora_logo); logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE); box.addView(logo,new LinearLayout.LayoutParams(dp(170),dp(170))); TextView title=text("Nexora",34,TEXT,true); title.setGravity(Gravity.CENTER); box.addView(title); TextView sub=text("Общение, музыка и творчество в одном пространстве.",15,MUTED,false); sub.setGravity(Gravity.CENTER); sub.setPadding(dp(18),dp(8),dp(18),dp(28)); box.addView(sub); Button login=button("Войти через Telegram",ACCENT); login.setOnClickListener(v->telegramAuth("login")); box.addView(login,new LinearLayout.LayoutParams(-1,dp(50))); Button register=button("Зарегистрироваться",SURFACE2); register.setOnClickListener(v->telegramAuth("register")); LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(50));rp.setMargins(0,dp(10),0,0);box.addView(register,rp); TextView note=text("Для подтверждения аккаунта откроется Telegram-бот.",12,MUTED,false);note.setGravity(Gravity.CENTER);note.setPadding(dp(10),dp(18),dp(10),0);box.addView(note);root.addView(box,new LinearLayout.LayoutParams(-1,-2));setContentView(root);animateIn(box); }
    private void telegramAuth(String action){ api.startTelegramAuth(action,new NexoraApiClient.Callback(){ public void onSuccess(JsonObject r){runOnUiThread(()->{String challenge=r.get("challenge").getAsString();String link=r.get("deep_link").getAsString();try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(link)));}catch(Exception e){} beginPoll(challenge);});} public void onError(Exception e){runOnUiThread(()->toast("Ошибка авторизации"));} }); }
    private void beginPoll(String challenge){if(authPoll!=null)handler.removeCallbacks(authPoll);final long started=System.currentTimeMillis();authPoll=new Runnable(){public void run(){if(System.currentTimeMillis()-started>300000){toast("Ссылка авторизации истекла");return;}api.pollTelegramAuth(challenge,new NexoraApiClient.Callback(){public void onSuccess(JsonObject r){runOnUiThread(()->{String st=r.has("status")?r.get("status").getAsString():"pending";if("approved".equals(st)){supabase.setSession(r.get("access_token").getAsString(),r.has("refresh_token")?r.get("refresh_token").getAsString():"");getPreferences(MODE_PRIVATE).edit().putBoolean("welcome_seen",true).apply();loadUserAndShowChats();}else if("rejected".equals(st)||"expired".equals(st))toast("Авторизация не завершена");else handler.postDelayed(authPoll,1200);});}public void onError(Exception e){handler.postDelayed(authPoll,1800);}});}};handler.post(authPoll);}

    private void showChats(){showShell("Чаты",0);sectionTitle("Чаты");EditText search=input("Поиск по чатам");content.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));content.addView(spacer(12)); if(userId==null){content.addView(info("Войдите в Nexora, чтобы видеть чаты."));return;} supabase.request("GET","/rest/v1/chat_members?select=chat_id,chat_rooms(id,name,updated_at,is_direct)&user_id=eq."+userId+"&order=joined_at.desc",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0){content.addView(info("Чатов пока нет. Добавьте друга и начните диалог."));return;}for(int i=0;i<a.size();i++){JsonObject row=a.get(i).getAsJsonObject();JsonObject room=row.has("chat_rooms")&&!row.get("chat_rooms").isJsonNull()?row.getAsJsonObject("chat_rooms"):null;if(room==null)continue;String id=room.get("id").getAsString();String name=room.has("name")&&!room.get("name").isJsonNull()?room.get("name").getAsString():"Личный чат";content.addView(chatRow(name,"Открыть диалог","C",v->showChat(id,name)));}}catch(Exception e){content.addView(info("Не удалось загрузить чаты."));}});}public void onError(Exception e){runOnUiThread(()->content.addView(info("Не удалось загрузить чаты.")));}}); }

    private void showFriends(){showShell("Друзья",1);sectionTitle("Друзья");EditText search=input("Найти по @нику");Button find=button("Найти",ACCENT);LinearLayout searchRow=new LinearLayout(this);searchRow.setGravity(Gravity.CENTER_VERTICAL);searchRow.addView(search,new LinearLayout.LayoutParams(0,dp(48),1));searchRow.addView(find,new LinearLayout.LayoutParams(dp(90),dp(48)));content.addView(searchRow);find.setOnClickListener(v->findUser(search.getText().toString().trim()));content.addView(spacer(12));sectionTitle("Мои друзья");loadFriendships();}
    private void findUser(String q){if(q.isEmpty())return;supabase.request("GET","/rest/v1/profiles?select=id,username,display_name,profile_type&username=ilike.*"+q.replace("@","")+"*&limit=10",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0){content.addView(info("Пользователь не найден."));return;}for(int i=0;i<a.size();i++){JsonObject p=a.get(i).getAsJsonObject();String id=p.get("id").getAsString();String name=p.has("display_name")&&!p.get("display_name").isJsonNull()?p.get("display_name").getAsString():p.get("username").getAsString();content.addView(actionRow(name,"@"+p.get("username").getAsString()+" · "+profileTypeLabel(p.get("profile_type").getAsString()),"Добавить",v->sendFriend(id)));}}catch(Exception ignored){}});}public void onError(Exception e){runOnUiThread(()->toast("Ошибка поиска"));}});}
    private void sendFriend(String id){JsonObject b=new JsonObject();b.addProperty("requester_id",userId);b.addProperty("addressee_id",id);b.addProperty("status","pending");supabase.request("POST","/rest/v1/friendships",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->toast("Заявка отправлена"));}public void onError(Exception e){runOnUiThread(()->toast("Не удалось отправить заявку"));}});}
    private void loadFriendships(){supabase.request("GET","/rest/v1/friendships?select=id,requester_id,addressee_id,status&or=(requester_id.eq."+userId+",addressee_id.eq."+userId+")&order=created_at.desc",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0){content.addView(info("Друзей пока нет."));return;}for(int i=0;i<a.size();i++){JsonObject f=a.get(i).getAsJsonObject();String other=f.get("requester_id").getAsString().equals(userId)?f.get("addressee_id").getAsString():f.get("requester_id").getAsString();String status=f.get("status").getAsString();content.addView(actionRow("Пользователь","ID: "+other+" · "+status,status.equals("pending")&&!f.get("requester_id").getAsString().equals(userId)?"Принять":"Чат",v->{if("pending".equals(status)&&!f.get("requester_id").getAsString().equals(userId))acceptFriend(f.get("id").getAsString());else createChat(other); }));}}catch(Exception ignored){}});}public void onError(Exception e){}});}
    private void acceptFriend(String id){JsonObject b=new JsonObject();b.addProperty("friendship_id",id);supabase.request("POST","/rest/v1/rpc/accept_friend",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){showFriends();}public void onError(Exception e){toast("Не удалось принять заявку");}});}
    private void createChat(String other){JsonObject b=new JsonObject();b.addProperty("other_user",other);supabase.request("POST","/rest/v1/rpc/create_direct_chat",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){try{String id=JsonParser.parseString(s).getAsJsonArray().get(0).getAsString();runOnUiThread(()->showChat(id,"Личный чат"));}catch(Exception e){toast("Не удалось создать чат");}}public void onError(Exception e){toast("Не удалось создать чат");}});}

    private void showSettings(){showShell("Настройки",2);sectionTitle("Настройки");content.addView(setting("Уведомления","Сообщения и события Nexora","ON"));content.addView(setting("Приватность","Контроль видимости профиля","›"));content.addView(setting("Сервисы","Telegram подключён","✓"));Button out=button("Выйти из аккаунта",Color.rgb(52,54,65));out.setOnClickListener(v->{supabase.signOut();getPreferences(MODE_PRIVATE).edit().putBoolean("welcome_seen",false).apply();showWelcome();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(0,dp(18),0,0);content.addView(out,p);}

    private void showProfile(){showShell("Профиль",3);sectionTitle("Профиль");supabase.getCurrentProfile(new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->renderProfile(s));}public void onError(Exception e){runOnUiThread(()->content.addView(info("Профиль недоступен.")));}});}
    private void renderProfile(String s){try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0){content.addView(info("Профиль ещё не создан."));return;}JsonObject p=a.get(0).getAsJsonObject();String name=p.has("display_name")&&!p.get("display_name").isJsonNull()?p.get("display_name").getAsString():"Nexora User";String username=p.has("username")&&!p.get("username").isJsonNull()?p.get("username").getAsString():"nexora";String type=p.has("profile_type")&&!p.get("profile_type").isJsonNull()?p.get("profile_type").getAsString():"user";
        LinearLayout hero=card();hero.setPadding(dp(18),dp(18),dp(18),dp(18));hero.setGravity(Gravity.CENTER_VERTICAL);ImageView av=new ImageView(this);av.setImageResource(R.drawable.nexora_logo);av.setScaleType(ImageView.ScaleType.CENTER_CROP);av.setBackground(round(ACCENT,40));hero.addView(av,new LinearLayout.LayoutParams(dp(72),dp(72)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.setPadding(dp(16),0,0,0);t.addView(text(name,19,TEXT,true));t.addView(text("@"+username,13,MUTED,false));t.addView(text(profileTypeLabel(type),13,ACCENT,true));hero.addView(t,new LinearLayout.LayoutParams(0,-2,1));content.addView(hero);
        Button edit=button("Изменить профиль",ACCENT);edit.setOnClickListener(v->showEditProfile(name,username,type));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(48));ep.setMargins(0,dp(10),0,0);content.addView(edit,ep);content.addView(spacer(12));
        sectionTitle("Тип аккаунта");LinearLayout types=new LinearLayout(this);types.setOrientation(LinearLayout.VERTICAL);Button regular=button("Обычный пользователь", "user".equals(type)?ACCENT:SURFACE2);Button artist=button("Исполнитель", "artist".equals(type)?ACCENT:SURFACE2);Button beat=button("Битмейкер", "beatmaker".equals(type)?ACCENT:SURFACE2);types.addView(regular,new LinearLayout.LayoutParams(-1,dp(46)));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(46));ap.setMargins(0,dp(8),0,0);types.addView(artist,ap);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(46));bp.setMargins(0,dp(8),0,0);types.addView(beat,bp);regular.setOnClickListener(v->updateType("user"));artist.setOnClickListener(v->updateType("artist"));beat.setOnClickListener(v->updateType("beatmaker"));content.addView(types);
        sectionTitle("Привязанные сервисы");content.addView(setting("Telegram","Используется для входа","✓"));content.addView(setting("Supabase","Аккаунт Nexora","✓"));
    }catch(Exception e){content.addView(info("Не удалось загрузить профиль."));}}
    private String profileTypeLabel(String type){if("artist".equals(type))return "Исполнитель";if("beatmaker".equals(type))return "Битмейкер";return "Обычный пользователь";}
    private void updateType(String type){JsonObject b=new JsonObject();b.addProperty("profile_type",type);supabase.request("PATCH","/rest/v1/profiles?id=eq."+userId,b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(MainActivity.this::showProfile);}public void onError(Exception e){toast("Не удалось изменить тип аккаунта");}});}
    private void showEditProfile(String name,String username,String type){LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(8),0,dp(8),0);EditText nameInput=input("Имя");nameInput.setText(name);EditText userInput=input("Username");userInput.setText(username);form.addView(nameInput,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(-1,dp(52));up.setMargins(0,dp(10),0,dp(10));form.addView(userInput,up);TextView label=text("Тип аккаунта",13,MUTED,true);form.addView(label);LinearLayout types=new LinearLayout(this);types.setOrientation(LinearLayout.VERTICAL);Button regular=button("Обычный пользователь","user".equals(type)?ACCENT:SURFACE2);Button artist=button("Исполнитель","artist".equals(type)?ACCENT:SURFACE2);Button beat=button("Битмейкер","beatmaker".equals(type)?ACCENT:SURFACE2);types.addView(regular,new LinearLayout.LayoutParams(-1,dp(44)));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(44));ap.setMargins(0,dp(6),0,0);types.addView(artist,ap);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(44));bp.setMargins(0,dp(6),0,0);types.addView(beat,bp);form.addView(types);final String[] selected={type};regular.setOnClickListener(v->{selected[0]="user";regular.setBackground(round(ACCENT,16));artist.setBackground(round(SURFACE2,16));beat.setBackground(round(SURFACE2,16));});artist.setOnClickListener(v->{selected[0]="artist";regular.setBackground(round(SURFACE2,16));artist.setBackground(round(ACCENT,16));beat.setBackground(round(SURFACE2,16));});beat.setOnClickListener(v->{selected[0]="beatmaker";regular.setBackground(round(SURFACE2,16));artist.setBackground(round(SURFACE2,16));beat.setBackground(round(ACCENT,16));});AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Редактировать профиль").setView(form).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",null).create();dialog.setOnShowListener(v->{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{String newName=nameInput.getText().toString().trim();String newUsername=userInput.getText().toString().trim().replace("@","");if(newName.isEmpty()||newUsername.isEmpty()){toast("Заполните имя и username");return;}JsonObject b=new JsonObject();b.addProperty("display_name",newName);b.addProperty("username",newUsername);b.addProperty("profile_type",selected[0]);supabase.request("PATCH","/rest/v1/profiles?id=eq."+userId,b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){dialog.dismiss();runOnUiThread(MainActivity.this::showProfile);}public void onError(Exception e){toast("Не удалось сохранить профиль");}});});});dialog.show();}

    private void showChat(String chatId,String name){if(realtime!=null)realtime.close();openChatId=chatId;showShell(name,-1);navigation.setVisibility(View.GONE);sectionTitle(name);ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);scroll.addView(box);content.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));loadMessages(chatId,box,scroll);LinearLayout composer=new LinearLayout(this);composer.setGravity(Gravity.CENTER_VERTICAL);EditText input=input("Сообщение…");composer.addView(input,new LinearLayout.LayoutParams(0,dp(50),1));ImageView send=new ImageView(this);send.setImageResource(R.drawable.ic_send);send.setPadding(dp(13),dp(13),dp(13),dp(13));send.setBackground(round(SURFACE2,18));send.setOnClickListener(v->{String body=input.getText().toString().trim();if(body.isEmpty())return;JsonObject b=new JsonObject();b.addProperty("chat_id",chatId);b.addProperty("sender_id",userId);b.addProperty("body",body);supabase.request("POST","/rest/v1/messages",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{input.setText("");send.animate().scaleX(.88f).scaleY(.88f).setDuration(70).withEndAction(()->send.animate().scaleX(1f).scaleY(1f).setDuration(100).start()).start();});}public void onError(Exception e){runOnUiThread(()->toast("Не удалось отправить сообщение"));}});});composer.addView(send,new LinearLayout.LayoutParams(dp(52),dp(50)));content.addView(composer);TextView back=text("Назад",14,MUTED,false);back.setGravity(Gravity.CENTER_VERTICAL);back.setOnClickListener(v->{realtime.close();showChats();});content.addView(back,new LinearLayout.LayoutParams(-1,dp(42)));realtime.subscribeToMessages(chatId,supabase.getAccessToken(),new SupabaseRealtimeClient.Listener(){public void onInsert(JsonObject r){runOnUiThread(()->{String sender=r.has("sender_id")?r.get("sender_id").getAsString():"";String body=r.get("body").getAsString();box.addView(message(body,sender.equals(userId)));scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));});}public void onError(Throwable t){}});}
    private void loadMessages(String chatId,LinearLayout box,ScrollView scroll){supabase.request("GET","/rest/v1/messages?select=id,sender_id,body,created_at&chat_id=eq."+chatId+"&order=created_at.asc&limit=100",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();for(int i=0;i<a.size();i++){JsonObject m=a.get(i).getAsJsonObject();box.addView(message(m.get("body").getAsString(),m.get("sender_id").getAsString().equals(userId)));}scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));}catch(Exception ignored){}});}public void onError(Exception e){}});}

    private void showShell(String title,int selected){LinearLayout root=baseRoot();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(horizontal(),dp(8),horizontal(),dp(8));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.nexora_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);top.addView(logo,new LinearLayout.LayoutParams(dp(44),dp(44)));TextView titleView=text(title,19,TEXT,true);titleView.setPadding(dp(10),0,0,0);top.addView(titleView,new LinearLayout.LayoutParams(0,dp(48),1));ImageView prof=new ImageView(this);prof.setImageResource(R.drawable.ic_profile);prof.setPadding(dp(10),dp(10),dp(10),dp(10));prof.setBackground(round(SURFACE2,22));prof.setOnClickListener(v->showProfile());top.addView(prof,new LinearLayout.LayoutParams(dp(44),dp(44)));root.addView(top);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(horizontal(),0,horizontal(),dp(12));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(content,new ScrollView.LayoutParams(-1,-1));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));navigation=buildNavigation(selected);root.addView(navigation,new LinearLayout.LayoutParams(-1,dp(68)));setContentView(root);animateIn(content);}
    private LinearLayout buildNavigation(int selected){LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(horizontal(),dp(4),horizontal(),dp(4));nav.setBackgroundColor(Color.rgb(13,14,22));nav.addView(navItem("Чаты",R.drawable.ic_chat,selected==0,v->showChats()),weight());nav.addView(navItem("Друзья",R.drawable.ic_people,selected==1,v->showFriends()),weight());nav.addView(navItem("Настройки",R.drawable.ic_settings,selected==2,v->showSettings()),weight());nav.addView(navItem("Профиль",R.drawable.ic_profile,selected==3,v->showProfile()),weight());return nav;}
    private View navItem(String title,int iconRes,boolean selected,View.OnClickListener l){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setGravity(Gravity.CENTER);b.setOnClickListener(l);ImageView i=new ImageView(this);i.setImageResource(iconRes);i.setAlpha(selected?1f:.62f);i.setPadding(dp(4),dp(3),dp(4),dp(3));TextView t=text(title,10,selected?TEXT:MUTED,selected);t.setGravity(Gravity.CENTER);b.addView(i,new LinearLayout.LayoutParams(dp(28),dp(28)));b.addView(t);return b;}
    private View chatRow(String name,String preview,String icon,View.OnClickListener l){LinearLayout r=card();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(14),dp(12),dp(14),dp(12));r.setOnClickListener(l);TextView a=text(icon,22,TEXT,true);a.setGravity(Gravity.CENTER);a.setBackground(round(ACCENT,30));r.addView(a,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.setPadding(dp(14),0,0,0);t.addView(text(name,16,TEXT,true));t.addView(text(preview,12,MUTED,false));r.addView(t,new LinearLayout.LayoutParams(0,-2,1));margin(r,0,0,0,9);return r;}
    private View actionRow(String name,String sub,String action,View.OnClickListener l){LinearLayout r=(LinearLayout)chatRow(name,sub,"N",v->{});TextView b=text(action,12,ACCENT,true);b.setGravity(Gravity.CENTER);b.setPadding(dp(10),0,dp(10),0);b.setOnClickListener(l);r.addView(b,new LinearLayout.LayoutParams(dp(82),dp(42)));return r;}
    private View setting(String title,String sub,String right){LinearLayout r=card();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(16),dp(14),dp(16),dp(14));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(text(title,15,TEXT,true));t.addView(text(sub,12,MUTED,false));r.addView(t,new LinearLayout.LayoutParams(0,-2,1));r.addView(text(right,12,GREEN,true));margin(r,0,0,0,8);return r;}
    private View message(String body,boolean own){TextView b=text(body,14,TEXT,false);b.setPadding(dp(14),dp(10),dp(14),dp(10));b.setBackground(round(own?ACCENT:SURFACE2,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.gravity=own?Gravity.END:Gravity.START;p.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(p);return b;}
    private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setSingleLine(true);e.setPadding(dp(16),0,dp(16),0);e.setBackground(round(SURFACE2,22));return e;}
    private View info(String s){TextView t=text(s,14,MUTED,false);t.setPadding(dp(16),dp(16),dp(16),dp(16));t.setBackground(round(SURFACE,16));margin(t,0,0,0,10);return t;}
    private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setBackground(round(SURFACE,18));return l;}
    private Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(14);b.setAllCaps(false);b.setBackground(round(c,16));return b;}
    private TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return t;}
    private LinearLayout baseRoot(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(BG);applyInsets(r);return r;}
    private void applyInsets(View r){if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);r.setOnApplyWindowInsetsListener((v,i)->{int top=Build.VERSION.SDK_INT>=30?i.getInsets(WindowInsets.Type.statusBars()).top:i.getSystemWindowInsetTop();int bottom=Build.VERSION.SDK_INT>=30?i.getInsets(WindowInsets.Type.navigationBars()).bottom:i.getSystemWindowInsetBottom();v.setPadding(0,top,0,bottom);return i;});}
    private int horizontal(){int w=getResources().getDisplayMetrics().widthPixels;return dp(w>=900?32:w>=600?24:16);}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,-1,1);}private View spacer(int d){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,dp(d)));return v;}private void sectionTitle(String s){TextView t=text(s,28,TEXT,true);t.setPadding(0,dp(12),0,dp(14));content.addView(t);}private void margin(View v,int l,int t,int r,int b){if(v.getLayoutParams() instanceof LinearLayout.LayoutParams){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)v.getLayoutParams();p.setMargins(dp(l),dp(t),dp(r),dp(b));v.setLayoutParams(p);}}private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private void animateIn(View v){v.setAlpha(0);v.setTranslationY(dp(8));v.animate().alpha(1).translationY(0).setDuration(240).setInterpolator(new AccelerateDecelerateInterpolator()).start();}private void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}
}
