package com.nexora.music;

import android.app.*;
import android.content.*;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaPlayer;
import android.net.Uri;
import android.os.*;
import android.provider.OpenableColumns;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import android.text.*;
import android.text.InputType;
import com.google.gson.*;
import java.util.*;

public class MainActivity extends Activity {
    private static final int BG=Color.rgb(5,10,17), LIGHT=Color.rgb(246,248,251), SURFACE=Color.rgb(15,23,33), SURFACE2=Color.rgb(23,33,46), TEXT=Color.rgb(244,248,252), MUTED=Color.rgb(142,157,174), CYAN=Color.rgb(51,210,238), BLUE=Color.rgb(75,125,255), VIOLET=Color.rgb(149,83,255), GREEN=Color.rgb(65,215,119), RED=Color.rgb(255,91,112);
    private SupabaseClient supabase; private NexoraApiClient api; private SupabaseRealtimeClient realtime;
    private LinearLayout content,nav; private String userId; private boolean dark=true; private MediaPlayer player; private TextView miniTitle; private LinearLayout miniPlayer;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final Typeface regular=Typeface.create("sans-serif",Typeface.NORMAL), bold=Typeface.create("sans-serif-medium",Typeface.BOLD);
    private Uri pendingAudioUri; private String pendingAudioName="",pendingAudioMime="",pendingAudioKind="track"; private EditText audioTitle,audioGenre,audioBpm,audioKey,audioDetune; private TextView audioFile;

    @Override protected void onCreate(Bundle state){super.onCreate(state);supabase=new SupabaseClient(this);api=new NexoraApiClient();realtime=new SupabaseRealtimeClient();dark=getPreferences(0).getBoolean("dark_theme",true);configureSystemBars();splash();}
    @Override protected void onDestroy(){stopPlayer();if(realtime!=null)realtime.close();handler.removeCallbacksAndMessages(null);super.onDestroy();}

    private void splash(){
        LinearLayout root=base();root.setGravity(Gravity.CENTER);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.nexora_mark);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);root.addView(logo,new LinearLayout.LayoutParams(dp(118),dp(118)));
        TextView title=txt("Nexora",30,TEXT,true);title.setGravity(Gravity.CENTER);root.addView(title);TextView ver=txt("v1.4.0",11,MUTED,false);ver.setGravity(Gravity.CENTER);root.addView(ver);setContentView(root);
        logo.setAlpha(0);logo.setScaleX(.84f);logo.setScaleY(.84f);title.setAlpha(0);ver.setAlpha(0);logo.animate().alpha(1).scaleX(1).scaleY(1).setDuration(280).start();title.animate().alpha(1).setStartDelay(120).setDuration(220).start();ver.animate().alpha(1).setStartDelay(180).setDuration(220).start();
        handler.postDelayed(()->{if(supabase.isSignedIn())loadUser();else showWelcome();},650);
    }
    private void configureSystemBars(){Window w=getWindow();w.setStatusBarColor(dark?BG:LIGHT);w.setNavigationBarColor(dark?BG:LIGHT);if(Build.VERSION.SDK_INT>=23)w.getDecorView().setSystemUiVisibility(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);}
    private void inset(View root){root.setOnApplyWindowInsetsListener((v,i)->{int top=i.getSystemWindowInsetTop(),bottom=i.getSystemWindowInsetBottom();v.setPadding(v.getPaddingLeft(),v.getPaddingTop()+top,v.getPaddingRight(),v.getPaddingBottom()+bottom);return i;});root.requestApplyInsets();}

    private void loadUser(){supabase.getCurrentUser(new SupabaseClient.Callback(){public void onSuccess(String s){try{userId=JsonParser.parseString(s).getAsJsonObject().get("id").getAsString();touchPresence();runOnUiThread(MainActivity.this::showChats);}catch(Exception e){showWelcome();}}public void onError(Exception e){supabase.signOut();showWelcome();}});}
    private void touchPresence(){JsonObject b=new JsonObject();b.addProperty("user_id",userId);b.addProperty("last_seen",new Date().toInstant().toString());supabase.request("POST","/rest/v1/user_presence?on_conflict=user_id",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){}public void onError(Exception e){}});}
    private void showWelcome(){
        LinearLayout r=base();r.setGravity(Gravity.CENTER);LinearLayout box=card();box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(24),dp(28),dp(24),dp(28));box.setGravity(Gravity.CENTER);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.nexora_mark);box.addView(logo,new LinearLayout.LayoutParams(dp(105),dp(105)));TextView h=txt("Nexora",30,TEXT,true);h.setGravity(Gravity.CENTER);box.addView(h);TextView sub=txt("Музыка • люди • творчество",13,MUTED,false);sub.setGravity(Gravity.CENTER);sub.setPadding(0,dp(7),0,dp(20));box.addView(sub);
        Button login=button("Войти через Telegram",CYAN);login.setTextColor(BG);login.setOnClickListener(v->telegram("login"));box.addView(login,new LinearLayout.LayoutParams(-1,dp(50)));Button reg=button("Регистрация",SURFACE2);reg.setOnClickListener(v->telegram("register"));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(0,dp(9),0,0);box.addView(reg,p);r.addView(box,new LinearLayout.LayoutParams(-1,-2));setContentView(r);animate(box);
    }
    private void telegram(String action){api.startTelegramAuth(action,new NexoraApiClient.Callback(){public void onSuccess(JsonObject r){try{String link=val(r,"deep_link");if(!link.isEmpty())startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(link)));}catch(Exception ignored){}String c=val(r,"challenge");if(!c.isEmpty())pollTelegram(c);}public void onError(Exception e){toast("Ошибка авторизации");}});}
    private void pollTelegram(String challenge){handler.postDelayed(()->api.pollTelegramAuth(challenge,new NexoraApiClient.Callback(){public void onSuccess(JsonObject r){String status=val(r,"status");if("approved".equals(status)){supabase.setSession(val(r,"access_token"),val(r,"refresh_token"));loadUser();}else if("pending".equals(status))pollTelegram(challenge);}public void onError(Exception e){handler.postDelayed(()->pollTelegram(challenge),1800);}}),900);}

    private void shell(String title,int selected){
        LinearLayout root=base();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(14),0,dp(14),0);
        ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.nexora_mark);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);top.addView(logo,new LinearLayout.LayoutParams(dp(38),dp(38)));TextView h=txt(title,20,TEXT,true);h.setPadding(dp(10),0,0,0);top.addView(h,new LinearLayout.LayoutParams(0,dp(54),1));
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(4),dp(16),dp(16));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(content);root.addView(top,new LinearLayout.LayoutParams(-1,dp(58)));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        miniPlayer=new LinearLayout(this);miniPlayer.setGravity(Gravity.CENTER_VERTICAL);miniPlayer.setPadding(dp(10),dp(6),dp(8),dp(6));miniPlayer.setBackground(round(SURFACE2,18));miniPlayer.setVisibility(View.GONE);miniTitle=txt("",13,TEXT,true);miniPlayer.addView(miniTitle,new LinearLayout.LayoutParams(0,dp(44),1));ImageView pp=icon(android.R.drawable.ic_media_play,CYAN);pp.setOnClickListener(v->{if(player==null)return;if(player.isPlaying())player.pause();else player.start();});miniPlayer.addView(pp,new LinearLayout.LayoutParams(dp(44),dp(44)));root.addView(miniPlayer,new LinearLayout.LayoutParams(-1,dp(56)));
        nav=buildNav(selected);root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(root);inset(root);animate(content);
    }
    private LinearLayout buildNav(int selected){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(dp(8),dp(5),dp(8),dp(5));n.setBackground(round(SURFACE,26));n.addView(navItem("Поиск",R.drawable.ic_search,selected==-2,v->showSearch()),weight());n.addView(navItem("Чаты",R.drawable.ic_chat,selected==0,v->showChats()),weight());n.addView(navItem("Друзья",R.drawable.ic_people,selected==1,v->showFriends()),weight());n.addView(navItem("Настройки",R.drawable.ic_settings,selected==2,v->showSettings()),weight());n.addView(navItem("Профиль",R.drawable.ic_profile,selected==3,v->showProfile()),weight());return n;}
    private View navItem(String title,int res,boolean selected,View.OnClickListener listener){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setGravity(Gravity.CENTER);ImageView i=icon(res,selected?CYAN:MUTED);TextView t=txt(title,9,selected?TEXT:MUTED,selected);t.setGravity(Gravity.CENTER);b.addView(i,new LinearLayout.LayoutParams(-1,dp(30)));b.addView(t);b.setOnClickListener(v->{v.animate().scaleX(.92f).scaleY(.92f).setDuration(55).withEndAction(()->v.animate().scaleX(1).scaleY(1).setDuration(100).start()).start();listener.onClick(v);});return b;}

    private void showChats(){shell("Чаты",0);TextView intro=txt("Твои диалоги",13,MUTED,false);content.addView(intro);LinearLayout fav=chatRow("Избранное","Личные заметки и сохранённые сообщения",true);fav.setOnClickListener(v->showFavorite());content.addView(fav);content.addView(spacer(8));
        supabase.request("GET","/rest/v1/chat_members?select=chat_id,chat_rooms(id,name,updated_at)&user_id=eq."+userId+"&order=joined_at.desc",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0)content.addView(empty("Чатов пока нет","Открой раздел друзей и начни диалог."));for(JsonElement e:a){JsonObject r=e.getAsJsonObject();JsonObject room=r.has("chat_rooms")&&!r.get("chat_rooms").isJsonNull()?r.getAsJsonObject("chat_rooms"):null;if(room==null)continue;String id=val(room,"id"),name=val(room,"name");if(name.isEmpty())name="Личный чат";LinearLayout row=chatRow(name,"Последний диалог",false);row.setOnClickListener(v->showChat(id,name));content.addView(row);}}catch(Exception ignored){}});}public void onError(Exception e){runOnUiThread(()->content.addView(empty("Не удалось загрузить чаты","Проверь соединение и попробуй ещё раз.")));}});
    }
    private void showFavorite(){shell("Избранное",-1);content.addView(txt("Пиши сюда всё, что не хочешь потерять",13,MUTED,false));LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(list);content.addView(sc,new LinearLayout.LayoutParams(-1,0,1));String saved=getPreferences(MODE_PRIVATE).getString("favorite_notes","");if(saved.isEmpty())list.addView(empty("Избранное пусто","Напиши заметку ниже."));else for(String line:saved.split("\\n",-1))if(!line.isEmpty())list.addView(message(line,true));LinearLayout composer=composer("Напиши себе…");content.addView(composer);EditText input=(EditText)composer.getTag();ImageView send=(ImageView)composer.getChildAt(1);send.setOnClickListener(v->{String body=input.getText().toString().trim();if(body.isEmpty())return;String next=saved.isEmpty()?body:saved+"\n"+body;getPreferences(MODE_PRIVATE).edit().putString("favorite_notes",next).apply();input.setText("");list.addView(message(body,true));sc.post(()->sc.fullScroll(View.FOCUS_DOWN));});}

    private void showFriends(){shell("Друзья",1);content.addView(txt("Твои друзья",13,MUTED,false));supabase.request("GET","/rest/v1/friendships?select=id,requester_id,addressee_id,status&status=eq.accepted&or=(requester_id.eq."+userId+",addressee_id.eq."+userId+")&order=created_at.desc",null,new SupabaseClient.Callback(){public void onSuccess(String s){try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0){runOnUiThread(()->content.addView(friendEmpty()));return;}for(JsonElement e:a){JsonObject f=e.getAsJsonObject();String other=userId.equals(val(f,"requester_id"))?val(f,"addressee_id"):val(f,"requester_id");loadFriend(other,val(f,"id"));}}catch(Exception ignored){}}public void onError(Exception e){runOnUiThread(()->content.addView(friendEmpty()));}});}
    private void loadFriend(String id,String friendshipId){supabase.request("GET","/rest/v1/profiles?select=id,username,display_name,avatar_url,is_artist,is_beatmaker&id=eq."+id+"&limit=1",null,new SupabaseClient.Callback(){public void onSuccess(String s){try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0)return;JsonObject p=a.get(0).getAsJsonObject();runOnUiThread(()->friendRow(p,id,friendshipId));}catch(Exception ignored){}}public void onError(Exception e){}});}
    private void friendRow(JsonObject p,String id,String fid){LinearLayout r=card();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(10),dp(10),dp(7),dp(10));r.addView(avatar(val(p,"display_name")),new LinearLayout.LayoutParams(dp(50),dp(50)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(dp(12),0,dp(8),0);TextView name=txt(val(p,"display_name"),15,TEXT,true);name.setOnClickListener(v->showPublicProfile(id));info.addView(name);info.addView(txt("@"+val(p,"username"),11,MUTED,false));TextView status=txt("● оффлайн",11,MUTED,false);checkOnline(id,status);info.addView(status);r.addView(info,new LinearLayout.LayoutParams(0,-2,1));ImageView chat=icon(R.drawable.ic_chat,CYAN);chat.setOnClickListener(v->createChat(id));r.addView(chat,new LinearLayout.LayoutParams(dp(42),dp(42)));ImageView more=icon(R.drawable.ic_more,MUTED);more.setOnClickListener(v->friendMenu(id,fid));r.addView(more,new LinearLayout.LayoutParams(dp(42),dp(42)));margin(r,0,0,0,7);content.addView(r);}
    private void checkOnline(String id,TextView out){supabase.request("GET","/rest/v1/user_presence?select=last_seen&user_id=eq."+id+"&limit=1",null,new SupabaseClient.Callback(){public void onSuccess(String s){try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()>0&&System.currentTimeMillis()-parseDate(val(a.get(0).getAsJsonObject(),"last_seen"))<300000)runOnUiThread(()->{out.setText("● в сети");out.setTextColor(GREEN);});}catch(Exception ignored){}}public void onError(Exception e){}});}
    private void friendMenu(String id,String fid){new AlertDialog.Builder(this).setItems(new String[]{"Удалить","Добавить в чёрный список"},(d,w)->{if(w==0){supabase.request("DELETE","/rest/v1/friendships?id=eq."+fid,null,new SupabaseClient.Callback(){public void onSuccess(String s){showFriends();}public void onError(Exception e){toast("Не удалось удалить");}});}else{JsonObject b=new JsonObject();b.addProperty("blocker_id",userId);b.addProperty("blocked_id",id);supabase.request("POST","/rest/v1/user_blocks",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){supabase.request("DELETE","/rest/v1/friendships?id=eq."+fid,null,new SupabaseClient.Callback(){public void onSuccess(String x){showFriends();}public void onError(Exception e){}});}public void onError(Exception e){toast("Не удалось заблокировать");}});}}).show();}
    private View friendEmpty(){LinearLayout c=card();c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(24),dp(36),dp(24),dp(36));TextView arrow=txt("↓",42,CYAN,true);arrow.setGravity(Gravity.CENTER);c.addView(arrow);c.addView(txt("Друзей пока нет",19,TEXT,true));TextView sub=txt("Открой поиск снизу и найди людей по @username.",13,MUTED,false);sub.setGravity(Gravity.CENTER);c.addView(sub);return c;}

    private void showSearch(){shell("Поиск",-2);content.removeAllViews();content.addView(txt("Поиск по Nexora",20,TEXT,true));content.addView(txt("@ пользователь • # тег • обычный текст",12,MUTED,false));nav.removeAllViews();nav.setPadding(dp(8),dp(6),dp(8),dp(6));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackground(round(SURFACE2,25));EditText q=input("Например @user-123 или #rock");q.setTextSize(16);TextView close=txt("×",28,MUTED,true);close.setGravity(Gravity.CENTER);bar.addView(q,new LinearLayout.LayoutParams(0,dp(56),1));bar.addView(close,new LinearLayout.LayoutParams(dp(50),dp(56)));nav.addView(bar,new LinearLayout.LayoutParams(-1,dp(60)));close.setOnClickListener(v->{hideKeyboard(q);showChats();});q.requestFocus();q.postDelayed(()->showKeyboard(q),140);q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){runSearch(s.toString().trim());}public void afterTextChanged(Editable e){}});}
    private void runSearch(String q){if(q.length()<2)return;while(content.getChildCount()>2)content.removeViewAt(2);String term=q.startsWith("@")?q.substring(1):q.startsWith("#")?q.substring(1):q;String path;if(q.startsWith("@"))path="/rest/v1/profiles?select=id,username,display_name,is_artist,is_beatmaker&username=ilike.*"+term+"*&is_hidden=eq.false&limit=30";else if(q.startsWith("#"))path="/rest/v1/posts?select=*&body=ilike.*%23"+term+"*&order=created_at.desc&limit=30";else path="/rest/v1/messages?select=*&body=ilike.*"+term+"*&order=created_at.desc&limit=30";supabase.request("GET",path,null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->renderSearch(s,q.startsWith("@"),q.startsWith("#")));}public void onError(Exception e){}});}
    private void renderSearch(String s,boolean users,boolean posts){try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0){content.addView(empty("Ничего не найдено","Попробуй другой запрос."));return;}for(JsonElement e:a){JsonObject o=e.getAsJsonObject();if(users){TextView row=txt(val(o,"display_name")+"\n@"+val(o,"username")+"  "+profileType(o),15,TEXT,true);row.setPadding(dp(15),dp(13),dp(15),dp(13));row.setBackground(round(SURFACE,18));row.setOnClickListener(v->showPublicProfile(val(o,"id")));content.addView(row);}else content.addView(postCard(posts?"Пост":"Сообщение",val(o,"body")));}}catch(Exception ignored){}}

    private void showSettings(){shell("Настройки",2);section("Профиль");settingButton("Редактирование профиля","Имя, username, о себе, Telegram-канал",v->profileSettings());settingButton("Другие сервисы","SoundCloud, Spotify, Яндекс Музыка, BeatChain",v->serviceSettings());section("Оформление");LinearLayout theme=settingRow("Тема","Чёрная / белая");Switch sw=new Switch(this);sw.setChecked(dark);sw.setOnCheckedChangeListener((b,c)->{dark=c;getPreferences(0).edit().putBoolean("dark_theme",c).apply();configureSystemBars();showSettings();});theme.addView(sw,new LinearLayout.LayoutParams(-2,-2));content.addView(theme);section("Приватность");settingButton("Приватность","Уведомления, видимость профиля и скрытые разделы",v->privacyDialog());section("Тип профиля");content.addView(profileTypeSelector());section("Данные");settingButton("Очистить кэш","Удалить локальные данные интерфейса",v->{getPreferences(0).edit().remove("favorite_notes").apply();toast("Кэш очищен");});section("Аккаунт");Button out=button("Выйти из аккаунта",Color.rgb(65,28,40));out.setTextColor(RED);out.setOnClickListener(v->{supabase.signOut();showWelcome();});content.addView(out,new LinearLayout.LayoutParams(-1,dp(50)));Button del=button("Удалить аккаунт",Color.rgb(55,25,30));del.setTextColor(RED);del.setOnClickListener(v->confirmDelete());LinearLayout.LayoutParams dpd=new LinearLayout.LayoutParams(-1,dp(50));dpd.setMargins(0,dp(8),0,0);content.addView(del,dpd);}
    private void profileSettings(){supabase.getCurrentProfile(new SupabaseClient.Callback(){public void onSuccess(String s){try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()>0)runOnUiThread(()->profileDialog(a.get(0).getAsJsonObject()));}catch(Exception ignored){}}public void onError(Exception e){toast("Не удалось загрузить профиль");}});}
    private void profileDialog(JsonObject p){LinearLayout f=form();EditText name=field("Имя",val(p,"display_name")),un=field("Username",val(p,"username")),bio=field("О себе",val(p,"bio")),tg=field("Telegram-канал",val(p,"telegram_channel_url"));f.addView(name);f.addView(un);f.addView(bio);f.addView(tg);new AlertDialog.Builder(this).setTitle("Редактирование профиля").setView(f).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",(d,w)->{String username=un.getText().toString().trim().replace("@","");JsonObject b=new JsonObject();b.addProperty("display_name",name.getText().toString().trim());if(username.isEmpty())b.add("username",JsonNull.INSTANCE);else b.addProperty("username",username);b.addProperty("bio",bio.getText().toString().trim());b.addProperty("telegram_channel_url",tg.getText().toString().trim());b.addProperty("is_hidden",username.isEmpty());supabase.request("PATCH","/rest/v1/profiles?id=eq."+userId,b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){toast("Профиль сохранён");showProfile();}public void onError(Exception e){toast("Не удалось сохранить профиль");}});}).show();}
    private void serviceSettings(){String[] n={"SoundCloud","Spotify","Яндекс Музыка","BeatChain"},p={"soundcloud","spotify","yandex_music","beatchain"};new AlertDialog.Builder(this).setTitle("Музыкальные сервисы").setItems(n,(d,w)->editService(p[w],n[w])).show();}
    private void editService(String platform,String title){EditText e=input("https://...");supabase.request("GET","/rest/v1/social_links?select=url&profile_id=eq."+userId+"&platform=eq."+platform+"&limit=1",null,new SupabaseClient.Callback(){public void onSuccess(String s){try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()>0)e.setText(val(a.get(0).getAsJsonObject(),"url"));}catch(Exception ignored){}}public void onError(Exception x){}});new AlertDialog.Builder(this).setTitle(title).setMessage("Только публичная ссылка. Пароль или OAuth-доступ не нужны.").setView(e).setNegativeButton("Удалить",(d,w)->supabase.request("DELETE","/rest/v1/social_links?profile_id=eq."+userId+"&platform=eq."+platform,null,new SupabaseClient.Callback(){public void onSuccess(String s){toast("Сервис удалён");}public void onError(Exception x){}})).setPositiveButton("Сохранить",(d,w)->{String u=e.getText().toString().trim();if(!validService(platform,u)){toast("Неверная ссылка");return;}JsonObject b=new JsonObject();b.addProperty("profile_id",userId);b.addProperty("platform",platform);b.addProperty("url",u);supabase.request("POST","/rest/v1/social_links?on_conflict=profile_id,platform",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){toast("Сервис привязан");}public void onError(Exception x){toast("Не удалось сохранить");}});}).show();}
    private void privacyDialog(){LinearLayout f=form();Switch notifications=new Switch(this);notifications.setText("Уведомления");notifications.setTextColor(TEXT);notifications.setChecked(true);Switch hidden=new Switch(this);hidden.setText("Скрыть профиль");hidden.setTextColor(TEXT);Switch sections=new Switch(this);sections.setText("Скрыть музыкальные разделы");sections.setTextColor(TEXT);Switch liked=new Switch(this);liked.setText("Скрыть понравившуюся музыку");liked.setTextColor(TEXT);f.addView(notifications);f.addView(hidden);f.addView(sections);f.addView(liked);new AlertDialog.Builder(this).setTitle("Приватность").setView(f).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",(d,w)->{JsonObject b=new JsonObject();b.addProperty("notifications_enabled",notifications.isChecked());b.addProperty("is_hidden",hidden.isChecked());b.addProperty("hide_music_sections",sections.isChecked());b.addProperty("hide_liked_music",liked.isChecked());supabase.request("PATCH","/rest/v1/profiles?id=eq."+userId,b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){toast("Приватность сохранена");}public void onError(Exception e){toast("Не удалось сохранить");}});}).show();}
    private LinearLayout profileTypeSelector(){LinearLayout box=card();box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(5),dp(14),dp(5));addRole(box,"Исполнитель","artist");addRole(box,"Битмейкер","beatmaker");return box;}
    private void addRole(LinearLayout box,String title,String key){CheckBox c=new CheckBox(this);c.setText(title);c.setTextColor(TEXT);c.setTextSize(15);if(Build.VERSION.SDK_INT>=21)c.setButtonTintList(ColorStateList.valueOf(CYAN));c.setChecked(getPreferences(0).getBoolean("role_"+key,false));c.setOnCheckedChangeListener((b,v)->{getPreferences(0).edit().putBoolean("role_"+key,v).apply();saveRoles();});box.addView(c,new LinearLayout.LayoutParams(-1,dp(52)));}
    private void saveRoles(){boolean artist=getPreferences(0).getBoolean("role_artist",false),beat=getPreferences(0).getBoolean("role_beatmaker",false);JsonObject b=new JsonObject();b.addProperty("is_artist",artist);b.addProperty("is_beatmaker",beat);b.addProperty("profile_type",artist&&beat?"artist_beatmaker":artist?"artist":beat?"beatmaker":"user");supabase.request("PATCH","/rest/v1/profiles?id=eq."+userId,b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){toast("Тип профиля сохранён");}public void onError(Exception e){toast("Не удалось сохранить тип профиля");}});}
    private void confirmDelete(){new AlertDialog.Builder(this).setTitle("Удалить аккаунт?").setMessage("Будут удалены профиль и связанные данные.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->supabase.request("POST","/rest/v1/rpc/delete_my_account","{}",new SupabaseClient.Callback(){public void onSuccess(String s){supabase.signOut();showWelcome();}public void onError(Exception e){toast("Удаление не выполнено");}})).show();}

    private void showProfile(){showPublicProfile(userId);}
    private void showPublicProfile(String id){shell(id.equals(userId)?"Профиль":"Профиль пользователя",3);supabase.request("GET","/rest/v1/profiles?select=*&id=eq."+id+"&limit=1",null,new SupabaseClient.Callback(){public void onSuccess(String s){try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()>0)runOnUiThread(()->renderProfile(a.get(0).getAsJsonObject(),id.equals(userId)));}catch(Exception ignored){}}public void onError(Exception e){}});}
    private void renderProfile(JsonObject p,boolean own){String name=val(p,"display_name");LinearLayout hero=card();hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER);hero.setPadding(dp(18),dp(18),dp(18),dp(18));hero.addView(avatar(name),new LinearLayout.LayoutParams(dp(88),dp(88)));hero.addView(txt(name.isEmpty()?"Nexora User":name,24,TEXT,true));String un=val(p,"username");if(!un.isEmpty())hero.addView(txt("@"+un,13,MUTED,false));String roles=profileType(p);if(!roles.isEmpty())hero.addView(txt(roles,12,CYAN,true));TextView bio=txt(val(p,"bio"),13,MUTED,false);bio.setGravity(Gravity.CENTER);hero.addView(bio);if(own){Button edit=button("Редактировать профиль",CYAN);edit.setTextColor(BG);edit.setOnClickListener(v->profileSettings());hero.addView(edit,new LinearLayout.LayoutParams(dp(220),dp(44)));}else{Button follow=button("Подписаться",CYAN);follow.setTextColor(BG);follow.setOnClickListener(v->follow(id));hero.addView(follow,new LinearLayout.LayoutParams(dp(170),dp(44)));}content.addView(hero);stats(id);section("Сервисы");loadServices(id);section("Треки");loadTracks(id,own,"track");section("Биты");loadTracks(id,own,"beat");section("Посты");loadPosts(id);}
    private void stats(String id){LinearLayout s=card();s.setPadding(dp(8),dp(12),dp(8),dp(12));TextView f=stat("—","подписчиков"),t=stat("—","треков / битов"),p=stat("—","прослушиваний");s.addView(f,weight());s.addView(t,weight());s.addView(p,weight());content.addView(s);supabase.request("GET","/rest/v1/follows?select=id&following_id=eq."+id+"&status=eq.accepted",null,new SupabaseClient.Callback(){public void onSuccess(String x){setStat(f,String.valueOf(count(x)),"подписчиков");}public void onError(Exception e){}});supabase.request("GET","/rest/v1/creator_tracks?select=plays&creator_id=eq."+id,null,new SupabaseClient.Callback(){public void onSuccess(String x){try{JsonArray a=JsonParser.parseString(x).getAsJsonArray();long plays=0;for(JsonElement e:a)if(e.getAsJsonObject().has("plays"))plays+=e.getAsJsonObject().get("plays").getAsLong();setStat(t,String.valueOf(a.size()),"треков / битов");setStat(p,formatNum(plays),"прослушиваний");}catch(Exception ignored){}}public void onError(Exception e){}});}
    private void loadServices(String id){supabase.request("GET","/rest/v1/social_links?select=platform,url&profile_id=eq."+id,null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0)return;LinearLayout row=new LinearLayout(MainActivity.this);row.setPadding(0,0,0,dp(5));int shown=Math.min(2,a.size());for(int i=0;i<shown;i++){JsonObject x=a.get(i).getAsJsonObject();TextView c=txt(serviceName(val(x,"platform")),13,TEXT,true);c.setGravity(Gravity.CENTER);c.setBackground(round(SURFACE,18));c.setOnClickListener(v->openUrl(val(x,"url")));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(58),1);p.setMargins(0,0,dp(5),0);row.addView(c,p);}if(a.size()>2){Button more=button("Ещё",SURFACE2);more.setOnClickListener(v->showAllServices(a));row.addView(more,new LinearLayout.LayoutParams(dp(74),dp(58)));}content.addView(row);}catch(Exception ignored){}});}public void onError(Exception e){}});}
    private void showAllServices(JsonArray a){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(JsonElement e:a){JsonObject x=e.getAsJsonObject();Button b=button(serviceName(val(x,"platform")),SURFACE2);b.setOnClickListener(v->openUrl(val(x,"url")));box.addView(b,new LinearLayout.LayoutParams(-1,dp(50)));}new AlertDialog.Builder(this).setTitle("Сервисы").setView(box).setNegativeButton("Закрыть",null).show();}
    private void loadTracks(String id,boolean own,String kind){supabase.request("GET","/rest/v1/creator_tracks?select=*&creator_id=eq."+id+"&kind=eq."+kind+"&order=created_at.desc&limit=3",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{JsonArray a=JsonParser.parseString(s).getAsJsonArray();if(a.size()==0){if(own)content.addView(empty(kind.equals("beat")?"Битов пока нет":"Треков пока нет",kind.equals("beat")?"Загрузи первый бит.":"Загрузи первый трек."));}for(JsonElement e:a)content.addView(trackCard(e.getAsJsonObject(),own));if(own){Button add=button(kind.equals("beat")?"+ Добавить бит":"+ Добавить трек",kind.equals("beat")?VIOLET:CYAN);if(kind.equals("track"))add.setTextColor(BG);add.setOnClickListener(v->addAudio(kind));content.addView(add,new LinearLayout.LayoutParams(-1,dp(48)));}if(a.size()>=3){Button more=button("Открыть ещё",SURFACE2);more.setOnClickListener(v->loadAllTracks(id,kind,own));content.addView(more,new LinearLayout.LayoutParams(-1,dp(44)));}}catch(Exception ignored){}});}public void onError(Exception e){}});}
    private void loadAllTracks(String id,String kind,boolean own){supabase.request("GET","/rest/v1/creator_tracks?select=*&creator_id=eq."+id+"&kind=eq."+kind+"&order=created_at.desc&limit=100",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{content.removeAllViews();for(JsonElement e:JsonParser.parseString(s).getAsJsonArray())content.addView(trackCard(e.getAsJsonObject(),own));if(own){Button add=button("+ Добавить",kind.equals("beat")?VIOLET:CYAN);add.setOnClickListener(v->addAudio(kind));content.addView(add);}}catch(Exception ignored){}});}public void onError(Exception e){}});}
    private View trackCard(JsonObject t,boolean own){LinearLayout r=card();r.setPadding(dp(10),dp(10),dp(8),dp(10));ImageView play=icon(android.R.drawable.ic_media_play,CYAN);play.setBackground(round(SURFACE2,22));r.addView(play,new LinearLayout.LayoutParams(dp(46),dp(46)));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),0,dp(8),0);c.addView(txt(val(t,"title"),15,TEXT,true));String meta=val(t,"genre");if(meta.isEmpty())meta="Без жанра";if("beat".equals(val(t,"kind"))){if(t.has("bpm"))meta+=" • "+val(t,"bpm")+" BPM";if(!val(t,"key_signature").isEmpty())meta+=" • "+val(t,"key_signature");if(!val(t,"detune").isEmpty())meta+=" • detune "+val(t,"detune");}else meta+=" • Трек";c.addView(txt(meta,11,MUTED,false));c.addView(wave());r.addView(c,new LinearLayout.LayoutParams(0,-2,1));play.setOnClickListener(v->playTrack(t));if(own){ImageView del=icon(R.drawable.ic_close,RED);del.setOnClickListener(v->confirmDeleteTrack(t));r.addView(del,new LinearLayout.LayoutParams(dp(42),dp(42)));}margin(r,0,0,0,8);return r;}
    private void playTrack(JsonObject t){String url=val(t,"audio_url");if(url.isEmpty()){toast("У этого элемента нет аудиофайла");return;}stopPlayer();player=new MediaPlayer();try{player.setDataSource(url);player.setOnPreparedListener(mp->{mp.start();showMini(val(t,"title"));incrementPlay(t);});player.setOnCompletionListener(mp->stopPlayer());player.setOnErrorListener((mp,w,e)->{toast("Не удалось воспроизвести аудио");stopPlayer();return true;});player.prepareAsync();}catch(Exception e){toast("Не удалось открыть аудио");stopPlayer();}}
    private void showMini(String title){if(miniPlayer!=null){miniPlayer.setVisibility(View.VISIBLE);miniTitle.setText(title);miniPlayer.setAlpha(0);miniPlayer.animate().alpha(1).setDuration(180).start();}}
    private void stopPlayer(){if(player!=null){try{if(player.isPlaying())player.stop();}catch(Exception ignored){}player.release();player=null;}if(miniPlayer!=null)miniPlayer.setVisibility(View.GONE);}
    private void incrementPlay(JsonObject t){String id=val(t,"id");if(id.isEmpty())return;long next=t.has("plays")&&!t.get("plays").isJsonNull()?t.get("plays").getAsLong()+1:1;JsonObject b=new JsonObject();b.addProperty("plays",next);supabase.request("PATCH","/rest/v1/creator_tracks?id=eq."+id,b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){}public void onError(Exception e){}});}
    private void addAudio(String kind){pendingAudioKind=kind;pendingAudioUri=null;LinearLayout f=form();audioTitle=field("Название","");audioGenre=field("Жанр","");audioKey=field("Тональность","");audioDetune=field("Детюн","");f.addView(audioTitle);f.addView(audioGenre);if("beat".equals(kind)){audioBpm=field("BPM","");f.addView(audioBpm);}else audioBpm=null;f.addView(audioKey);f.addView(audioDetune);Button choose=button("Выбрать MP3 / WAV",SURFACE2);f.addView(choose,new LinearLayout.LayoutParams(-1,dp(48)));audioFile=txt("Файл не выбран • до 50 МБ",11,MUTED,false);audioFile.setPadding(0,dp(8),0,dp(5));f.addView(audioFile);choose.setOnClickListener(v->pickAudio());AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Новый "+("beat".equals(kind)?"бит":"трек")).setView(f).setNegativeButton("Отмена",null).setPositiveButton("Загрузить",null).create();dialog.setOnShowListener(x->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(pendingAudioUri==null){toast("Выбери файл");return;}uploadAudio(dialog);}));dialog.show();}
    private void pickAudio(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("audio/*");startActivityForResult(i,1401);}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=1401||resultCode!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();String name="audio";try{android.database.Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null);if(c!=null){if(c.moveToFirst()&&!c.isNull(0))name=c.getString(0);c.close();}}catch(Exception ignored){}String mime=getContentResolver().getType(u);if(!NexoraStorage.isSupportedAudio(name,mime)){toast("Разрешены только MP3 и WAV");return;}pendingAudioUri=u;pendingAudioName=name;pendingAudioMime=mime==null?"audio/mpeg":mime;runOnUiThread(()->{if(audioFile!=null)audioFile.setText(name+" • готов к загрузке");});}
    private void uploadAudio(AlertDialog dialog){String title=audioTitle.getText().toString().trim();if(title.isEmpty()){toast("Укажи название");return;}if("beat".equals(pendingAudioKind)&&audioBpm.getText().toString().trim().isEmpty()){toast("Укажи BPM");return;}String path=userId+"/"+UUID.randomUUID()+NexoraStorage.safeExtension(pendingAudioName);toast("Загрузка…");new NexoraStorage(this,BuildConfig.SUPABASE_URL,BuildConfig.SUPABASE_PUBLISHABLE_KEY,supabase.getAccessToken()).uploadAudio(pendingAudioUri,path,pendingAudioMime,new NexoraStorage.Callback(){public void onSuccess(String url){JsonObject b=new JsonObject();b.addProperty("creator_id",userId);b.addProperty("title",title);b.addProperty("genre",audioGenre.getText().toString().trim());b.addProperty("kind",pendingAudioKind);b.addProperty("audio_url",url);if(!audioKey.getText().toString().trim().isEmpty())b.addProperty("key_signature",audioKey.getText().toString().trim());if(!audioDetune.getText().toString().trim().isEmpty())try{b.addProperty("detune",Double.parseDouble(audioDetune.getText().toString().trim()));}catch(Exception ignored){}if("beat".equals(pendingAudioKind))try{b.addProperty("bpm",Integer.parseInt(audioBpm.getText().toString().trim()));}catch(Exception ignored){}supabase.request("POST","/rest/v1/creator_tracks",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{dialog.dismiss();toast("Опубликовано");showProfile();});}public void onError(Exception e){toast("Не удалось сохранить запись");}});}public void onError(Exception e){toast("Не удалось загрузить: "+e.getMessage());}});}
    private void confirmDeleteTrack(JsonObject t){new AlertDialog.Builder(this).setTitle("Удалить?").setMessage("Аудиофайл и запись будут удалены.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->deleteTrack(t)).show();}
    private void deleteTrack(JsonObject t){String id=val(t,"id"),url=val(t,"audio_url");Runnable db=()->supabase.request("DELETE","/rest/v1/creator_tracks?id=eq."+id,null,new SupabaseClient.Callback(){public void onSuccess(String s){showProfile();}public void onError(Exception e){toast("Не удалось удалить запись");}});if(url.isEmpty()){db.run();return;}new NexoraStorage(this,BuildConfig.SUPABASE_URL,BuildConfig.SUPABASE_PUBLISHABLE_KEY,supabase.getAccessToken()).deletePublicAudio(url,new NexoraStorage.Callback(){public void onSuccess(String s){db.run();}public void onError(Exception e){db.run();}});}
    private void loadPosts(String id){supabase.request("GET","/rest/v1/posts?select=*&author_id=eq."+id+"&order=created_at.desc&limit=20",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{for(JsonElement e:JsonParser.parseString(s).getAsJsonArray())content.addView(postCard("Пост",val(e.getAsJsonObject(),"body")));}catch(Exception ignored){}});}public void onError(Exception e){}});}
    private void follow(String id){supabase.request("POST","/rest/v1/rpc/request_follow",jsonObj("target_user",id),new SupabaseClient.Callback(){public void onSuccess(String s){toast("Запрос на подписку отправлен");}public void onError(Exception e){toast("Не удалось отправить запрос");}});}

    private void showChat(String id,String name){if(realtime!=null)realtime.close();shell(name,-1);nav.setVisibility(View.GONE);ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);content.addView(sc,new LinearLayout.LayoutParams(-1,0,1));loadMessages(id,list,sc);LinearLayout composer=composer("Сообщение…");content.addView(composer);EditText input=(EditText)composer.getTag();ImageView send=(ImageView)composer.getChildAt(1);send.setOnClickListener(v->{String body=input.getText().toString().trim();if(body.isEmpty())return;JsonObject b=new JsonObject();b.addProperty("chat_id",id);b.addProperty("sender_id",userId);b.addProperty("body",body);supabase.request("POST","/rest/v1/messages",b.toString(),new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->input.setText(""));}public void onError(Exception e){toast("Не удалось отправить");}});});realtime.subscribeToMessages(id,supabase.getAccessToken(),new SupabaseRealtimeClient.Listener(){public void onInsert(JsonObject r){runOnUiThread(()->{String body=val(r,"body");if(!body.isEmpty()){list.addView(message(body,userId.equals(val(r,"sender_id"))));sc.post(()->sc.fullScroll(View.FOCUS_DOWN));}});}public void onError(Throwable t){}});}
    private void loadMessages(String id,LinearLayout list,ScrollView sc){supabase.request("GET","/rest/v1/messages?select=*&chat_id=eq."+id+"&order=created_at.asc&limit=100",null,new SupabaseClient.Callback(){public void onSuccess(String s){runOnUiThread(()->{try{for(JsonElement e:JsonParser.parseString(s).getAsJsonArray()){JsonObject m=e.getAsJsonObject();list.addView(message(val(m,"body"),userId.equals(val(m,"sender_id"))));}sc.post(()->sc.fullScroll(View.FOCUS_DOWN));}catch(Exception ignored){}});}public void onError(Exception e){}});}
    private void createChat(String other){supabase.request("POST","/rest/v1/rpc/create_direct_chat",jsonObj("other_user",other),new SupabaseClient.Callback(){public void onSuccess(String s){try{JsonElement e=JsonParser.parseString(s);String id=e.isJsonArray()?e.getAsJsonArray().get(0).getAsString():e.getAsString();runOnUiThread(()->showChat(id,"Личный чат"));}catch(Exception ignored){toast("Не удалось открыть чат");}}public void onError(Exception e){toast("Не удалось открыть чат");}});}

    private LinearLayout composer(String hint){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(5),dp(4),dp(4),dp(4));c.setBackground(round(SURFACE2,25));EditText e=input(hint);ImageView send=icon(R.drawable.ic_send,CYAN);send.setBackground(round(CYAN,22));send.setPadding(dp(12),dp(12),dp(12),dp(12));c.addView(e,new LinearLayout.LayoutParams(0,dp(52),1));c.addView(send,new LinearLayout.LayoutParams(dp(52),dp(52)));c.setTag(e);return c;}
    private View message(String body,boolean own){TextView t=txt(body,14,TEXT,false);t.setPadding(dp(14),dp(10),dp(14),dp(10));t.setBackground(round(own?Color.rgb(34,119,148):SURFACE2,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.gravity=own?Gravity.END:Gravity.START;p.setMargins(0,dp(4),0,dp(4));t.setLayoutParams(p);return t;}
    private LinearLayout chatRow(String name,String sub,boolean favorite){LinearLayout r=card();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(10),dp(10),dp(10),dp(10));TextView a=txt(favorite?"★":initial(name),19,TEXT,true);a.setGravity(Gravity.CENTER);a.setBackground(round(favorite?VIOLET:BLUE,20));r.addView(a,new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),0,0,0);c.addView(txt(name,15,TEXT,true));c.addView(txt(sub,11,MUTED,false));r.addView(c,new LinearLayout.LayoutParams(0,-2,1));return r;}
    private View postCard(String title,String body){LinearLayout r=card();r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(15),dp(13),dp(15),dp(13));r.addView(txt(title,11,CYAN,true));r.addView(txt(body,14,TEXT,false));margin(r,0,0,0,8);return r;}
    private View empty(String title,String sub){LinearLayout r=card();r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(24),dp(30),dp(24),dp(30));TextView n=txt("N",26,CYAN,true);n.setGravity(Gravity.CENTER);r.addView(n);r.addView(txt(title,18,TEXT,true));TextView s=txt(sub,12,MUTED,false);s.setGravity(Gravity.CENTER);r.addView(s);return r;}
    private TextView stat(String value,String label){TextView t=txt(value+"\n"+label,13,TEXT,true);t.setGravity(Gravity.CENTER);return t;}
    private void setStat(TextView v,String a,String b){runOnUiThread(()->v.setText(a+"\n"+b));}
    private String profileType(JsonObject p){boolean a=p.has("is_artist")&&!p.get("is_artist").isJsonNull()&&p.get("is_artist").getAsBoolean(),b=p.has("is_beatmaker")&&!p.get("is_beatmaker").isJsonNull()&&p.get("is_beatmaker").getAsBoolean();if(a&&b)return "Исполнитель • Битмейкер";if(a)return "Исполнитель";if(b)return "Битмейкер";return "";}
    private String serviceName(String p){if("soundcloud".equals(p))return "SoundCloud";if("spotify".equals(p))return "Spotify";if("yandex_music".equals(p))return "Яндекс Музыка";return "BeatChain";}
    private boolean validService(String p,String url){try{Uri u=Uri.parse(url);String h=u.getHost();if(h==null||!"https".equalsIgnoreCase(u.getScheme()))return false;h=h.toLowerCase(Locale.US);if("soundcloud".equals(p))return h.equals("soundcloud.com")||h.endsWith(".soundcloud.com");if("spotify".equals(p))return h.equals("open.spotify.com")||h.endsWith(".spotify.com");if("yandex_music".equals(p))return h.contains("music.yandex")||h.endsWith("yandex.ru")||h.endsWith("yandex.com");return h.contains("beatchain");}catch(Exception e){return false;}}
    private void openUrl(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception ignored){}}
    private String val(JsonObject o,String k){return o!=null&&o.has(k)&&!o.get(k).isJsonNull()?o.get(k).getAsString():"";}
    private String initial(String s){return s==null||s.trim().isEmpty()?"N":s.trim().substring(0,1).toUpperCase(Locale.getDefault());}
    private String jsonObj(String k,String v){JsonObject o=new JsonObject();o.addProperty(k,v);return o.toString();}
    private int count(String s){try{return JsonParser.parseString(s).getAsJsonArray().size();}catch(Exception e){return 0;}}
    private String formatNum(long n){if(n>=1000000)return String.format(Locale.US,"%.1fM",n/1000000d);if(n>=1000)return String.format(Locale.US,"%.1fK",n/1000d);return String.valueOf(n);}
    private long parseDate(String s){try{return new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSX",Locale.US).parse(s).getTime();}catch(Exception e){try{return new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssX",Locale.US).parse(s).getTime();}catch(Exception x){return 0;}}}
    private void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}
    private LinearLayout base(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(dark?BG:LIGHT);return r;}
    private LinearLayout card(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setBackground(round(SURFACE,20));return r;}
    private TextView txt(String s,int size,int color,boolean isBold){TextView t=new TextView(this);t.setText(s==null?"":s);t.setTextSize(size);t.setTextColor(dark?color:(color==TEXT?Color.rgb(20,27,35):color));t.setTypeface(isBold?bold:regular);return t;}
    private EditText input(String hint){EditText e=new EditText(this);e.setSingleLine(true);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextColor(dark?TEXT:Color.rgb(20,27,35));e.setTextSize(14);e.setPadding(dp(15),0,dp(15),0);e.setBackground(round(dark?SURFACE2:Color.WHITE,22));return e;}
    private EditText field(String hint,String value){EditText e=input(hint);e.setText(value);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setSingleLine(false);e.setMinLines(1);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(0,dp(4),0,dp(4));e.setLayoutParams(p);return e;}
    private LinearLayout form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(8),0,dp(8),0);return f;}
    private Button button(String label,int color){Button b=new Button(this);b.setText(label);b.setTextColor(TEXT);b.setTextSize(13);b.setAllCaps(false);b.setStateListAnimator(null);b.setBackground(round(color,20));return b;}
    private ImageView icon(int res,int tint){ImageView i=new ImageView(this);i.setImageResource(res);i.setColorFilter(tint);i.setScaleType(ImageView.ScaleType.CENTER);return i;}
    private View spacer(int d){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,dp(d)));return v;}
    private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,-1,1);}
    private void section(String s){TextView t=txt(s,21,TEXT,true);t.setPadding(0,dp(16),0,dp(8));content.addView(t);}
    private void settingButton(String title,String sub,View.OnClickListener l){LinearLayout r=settingRow(title,sub);r.setOnClickListener(l);content.addView(r);}
    private LinearLayout settingRow(String title,String sub){LinearLayout r=card();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(14),dp(12),dp(10),dp(12));LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.addView(txt(title,15,TEXT,true));c.addView(txt(sub,11,MUTED,false));r.addView(c,new LinearLayout.LayoutParams(0,-2,1));r.addView(txt("›",22,MUTED,true));margin(r,0,0,0,7);return r;}
    private GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private View wave(){LinearLayout w=new LinearLayout(this);w.setGravity(Gravity.CENTER_VERTICAL);for(int i=0;i<24;i++){View b=new View(this);b.setBackground(round(i%6==0?VIOLET:CYAN,3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(4),dp(4+(i*9%17)));p.setMargins(1,0,1,0);w.addView(b,p);}return w;}
    private void margin(View v,int l,int t,int r,int b){if(v.getLayoutParams() instanceof LinearLayout.LayoutParams){LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)v.getLayoutParams();p.setMargins(dp(l),dp(t),dp(r),dp(b));v.setLayoutParams(p);}}
    private void animate(View v){v.setAlpha(0);v.setTranslationY(dp(7));v.animate().alpha(1).translationY(0).setDuration(220).start();}
    private void showKeyboard(View v){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(v,InputMethodManager.SHOW_IMPLICIT);}
    private void hideKeyboard(View v){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
